name: reward-me
services:
  auth:
    build:
      context: ./packages/auth
      dockerfile: ./Dockerfile
      target: final
    environment:
      - PORT=8080
      - GITHUB_CLIENT_SECRET=f46876a845a711638e9e850c6596b712096588ed
      - GITHUB_CLIENT_ID=Iv1.88021bc17e7ff8f1
      - GOOGLE_JWK_AUDIENCE=1051199875564-o0hgcae38gs43ql0apo85uuh07dvn2n4.apps.googleusercontent.com
      - SIGNING_KEY=0xb8a59213d05b6e7f2d95d2a7d36379aae45dff57939185196a69caf2f84cc06d
    ports:
      - '8080:8080'
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: ./packages/app/Dockerfile
      target: production-stage
    environment:
      - PORT=80
    ports:
      - '3000:80'
    restart: unless-stopped
