[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-json-response = "0.1.3"
actix-web = "4"
const-hex = "1.9.1"
dotenv = "0.15.0"
ethers-core = "2.0.10"
ethers-signers = "2.0.10"
jsonwebtoken = "8.3.0"
reqwest = { version = "0.11.22", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
strum = "0.25.0"
strum_macros = "0.25.2"
